# Insipired by: https://github.com/spf13/cobra/blob/master/.github/workflows/test.yml
name: Test

on:
  push:
  pull_request:

env:
  GO111MODULE: on

jobs:
  golangci-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --verbose

  goreleaser-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check GoReleaser config
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: check

  dockerfile-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: Dockerfile
          verbose: true

      - name: Update Pull Request
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          script: |
            const output = `
            #### Hadolint: \`${{ steps.hadolint.outcome }}\`
            \`\`\`
            ${process.env.HADOLINT_RESULTS}
            \`\`\`
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-unix:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macOS]
        go: [17, 18]
    name: '${{ matrix.os }} | 1.${{ matrix.go }}.x'
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.${{ matrix.go }}.0'

      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-1.${{ matrix.go }}.x-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-1.${{ matrix.go }}.x-

      - run: go test -v

